version: '2.4'

volumes:
  data: {}

services:
  srv:
    build:
      dockerfile: Dockerfile.aarch64
      context: .
    volumes:
      - data:/etc/openvpn
    ports:
      - 1194:1194/tcp
    cap_add:
      - NET_ADMIN
    restart: always
