version: '2.4'

volumes:
  data: {}

services:
  srv:
    image: kylemanna/openvpn-aarch64
    volumes:
      - data:/etc/openvpn
    ports:
      - 443:1194/udp
    cap_add:
      - NET_ADMIN
    restart: always
